### ISSUE TITLE
Mysqli statement execute error

### ISSUE THREAD

**Issue by emmyceru** [utlib/BatchUpload#10]
Hi all, I just installed Omeka a few weeks ago, and have been playing around with it. I had hoped to batch import files with a csv, so I tried the plugin, but am encountering errors. I'm not too well versed in troubleshooting, so I'm not exactly sure what the following means. Any help would be appreciated.

Omeka has encountered an error
Zend_Db_Statement_Mysqli_Exception
Mysqli statement execute error : Column 'added' cannot be null

Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Column 'added' cannot be null in /home/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /home/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /home/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /home/application/libraries/Omeka/Db.php(257): Omeka_Db->__call('query', Array)
#4 /home/application/libraries/Omeka/Record/AbstractRecord.php(541): Omeka_Db->insert('omeka_batch_upl...', Array)
#5 /home/application/libraries/Omeka/Controller/AbstractActionController.php(188): Omeka_Record_AbstractRecord->save(false)
#6 /home/plugins/BatchUpload/controllers/JobsController.php(107): Omeka_Controller_AbstractActionController->addAction()
#7 /home/application/libraries/Zend/Controller/Action.php(516): BatchUpload_JobsController->addAction()
#8 /home/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#9 /home/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /home/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /home/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /home/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /home/admin/index.php(28): Omeka_Application->run()
#14 {main}

**Comment by dicksonlaw583** [comment]
Please install [the version of the plugin from the `dev-added-cannot-be-null` side branch](https://github.com/utlib/BatchUpload/tree/dev-added-cannot-be-null) and let me know how it goes.

**Comment by emmyceru** [comment]
Thanks. That at least got a little further than before. I had created a test csv file with only 2 items in it, and it gets to the "Batch Uploader | Processing Data Rows" stage, but doesn't appear to be able to progress beyond that. The status bar keeps moving, and says "please wait"

**Comment by dicksonlaw583** [comment]
Fixed in 1.1.0.
