### ISSUE TITLE
Importing multiple values

### ISSUE THREAD

**Issue by Witia1** [utlib/BatchUpload#2]
How to import multiple values from single field? For instance, creators separeted by a separator. I can map columns during importing (Creator 1 -> Creator, Creator 2 -> Creator). But unfortunately it is not a good solutions, because I have a CSV file, where all creators are in a single field.

**Comment by dicksonlaw583** [comment]
Could you try this branch? This contains a new column on the CSV mapping screen that allows you to specify an "internal separator" covering your use case.

https://github.com/utlib/BatchUpload/tree/dev-multi-subfields

**Comment by dicksonlaw583** [comment]
Added in 1.1.0.
