### ISSUE TITLE
Multi Subfields Bug Fix

### ISSUE THREAD

**Issue by Bosterm** [utlib/BatchUpload#4]
Hello, I was using this plugin to upload files, specifically the multi subfields experimental branch. While doing so I encountered a bug when uploading multiple files for one item. For some reason, it was creating empty files in addition to the right files, so that in the file upload step, it was expecting additional files that I could not provide.

Here is one of the records for an empty file in the batch_upload_rows table in the database:

`(48,16,2,'{\"file\":\"\",\"fileOrder\":2,\"fileId\":null,\"item\":45}')`

To fix it, I used the php [array_filter](https://secure.php.net/manual/en/function.array-filter.php) method to remove empty elements from the uploads array before the array was inserted into the database. This seems to have solved the problem.

I just submitted a pull request with my fix, if you want to use it.

**Comment by dicksonlaw583** [comment]
@Bosterm:

Thank you very much for providing this fix. The corresponding pull request has been merged.
