### ISSUE TITLE
Column 'added' cannot be null

### ISSUE THREAD

**Issue by allanaaa** [utlib/BatchUpload#7]
Hi,

Much like other plugins (https://github.com/scholarslab/Neatline/issues/400 and https://github.com/omeka/plugin-CsvImport/issues/60) I am getting the following error. 

> Zend_Db_Statement_Mysqli_Exception
> 
>     Mysqli statement execute error : Column 'added' cannot be null
> 
> Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Column 'added' cannot be null in /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
> Stack trace:
> 0 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
> 1 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
> 2 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
> 3 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Db.php(257): Omeka_Db->__call('query', Array)
> 4 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Record/AbstractRecord.php(541): Omeka_Db->insert('omeka_batch_upl...', Array)
> 5 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Controller/AbstractActionController.php(188): Omeka_Record_AbstractRecord->save(false)
> 6 /home/allmay3/allanaaa.com/omeka/plugins/BatchUpload/controllers/MappingSetsController.php(81): Omeka_Controller_AbstractActionController->addAction()
> 7 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Controller/Action.php(516): BatchUpload_MappingSetsController->addAction()
> 8 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
> 9 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
> 10 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
> 11 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
> 12 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
> 13 /home/allmay3/allanaaa.com/omeka/admin/index.php(28): Omeka_Application->run()
> 14 {main}

I'm on PHP 7.3 and MySQL 5.7. 

[On a separate install (also Omeka 2.7.1) on another web hosting service it works fine. It's using PHP 5.6.40 and MySQL 5.6.47 if that helps.]

I am sure a similar solution to the issues I linked above will work, but I am clueless as to where to insert it or what to edit. Thanks!

**Comment by dicksonlaw583** [comment]
Thank you for reporting this issue. Can you please try the branch cited in the PR below and let me know how it goes?

https://github.com/utlib/BatchUpload/pull/8

**Comment by allanaaa** [comment]
I'm sorry, now it's giving me



> Zend_Db_Statement_Mysqli_Exception
> 
>     Mysqli statement execute error : Column 'modified' cannot be null
> 
> Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Column 'modified' cannot be null in /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
> Stack trace:
> #0 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
> #1 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
> #2 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
> #3 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Db.php(257): Omeka_Db->__call('query', Array)
> #4 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Record/AbstractRecord.php(541): Omeka_Db->insert('omeka_batch_upl...', Array)
> #5 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Controller/AbstractActionController.php(188): Omeka_Record_AbstractRecord->save(false)
> #6 /home/allmay3/allanaaa.com/omeka/plugins/BatchUpload/controllers/JobsController.php(107): Omeka_Controller_AbstractActionController->addAction()
> #7 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Controller/Action.php(516): BatchUpload_JobsController->addAction()
> #8 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
> #9 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
> #10 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
> #11 /home/allmay3/allanaaa.com/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
> #12 /home/allmay3/allanaaa.com/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
> #13 /home/allmay3/allanaaa.com/omeka/admin/index.php(28): Omeka_Application->run()
> #14 {main}

**Comment by dicksonlaw583** [comment]
Updated. Can you please download and try again?

**Comment by allanaaa** [comment]
That moved us past the first hurdle. 

There was a false start when I started my first job: It froze on the "Please wait" screen while processing the import. You could see it on "Step 3 of 4" on the Jobs screen but it didn't seem to be processing (I left it for 20 minutes). No new items were being added. 

I deleted the job and started a fresh one with the same file, and that seems to be working fine. 

Also, a new error is showing at the top of the Mappings screen if you flip over there:

> Warning: Declaration of BatchUpload_MappingSetsController::_redirectAfterEdit() should be compatible with Omeka_Controller_AbstractActionController::_redirectAfterEdit($record) in /home/allmay3/allanaaa.com/omeka/plugins/BatchUpload/controllers/MappingSetsController.php on line 8

**Comment by allanaaa** [comment]
Update: the second job appears to have frozen on item 110 of 120.

**Comment by dicksonlaw583** [comment]
That error isn't fatal (it is only at the warning level), but I have fixed it anyways. Please download from the PR and retry.

The freeze at 110 items may be caused by exceeding the `max_execution_time` setting in your PHP installation. Please set it to a higher value to allow your entries to finish running. Alternatively, try running your job in smaller batches.

**Comment by allanaaa** [comment]
Thanks! That fixed both errors. No need to change the max_execution_time either; it ran very smoothly without it. 
Thank you, I really appreciate your efforts!
