### ISSUE TITLE
Process fails

### ISSUE THREAD

**Issue by lljohnston** [utlib/BatchUpload#9]
I used batch upload earlier today to load a collection using an old template with no problem. Im on Omeka Classic 2.7.1 hosted on Reclaim.

I’m mapping a new set of fields from a new set of CSV files with different column names. I start the batch process, identify which existing collection I’m loading into, select a CSV file, create and apply a template, and when I click on Next Step, it returns me to the CSV selection page again with no CSV file displayed. I select the same CSV again and apply the template I’ve already created and click Next Step, and back to square one again. I’m not getting an error message. Any thoughts? Something wrong with the CSV that I need to look for?

I just spotted an error message when I went to the Mapping tab:

/plugins/BatchUpload/controllers/MappingSetsController.php on line 8

Warning: Declaration of BatchUpload_MappingSetsController::_redirectAfterEdit() should be compatible with Omeka_Controller_AbstractActionController::_redirectAfterEdit($record) in /home/gallery1/public_html/plugins/BatchUpload/controllers/MappingSetsController.php on line 8

I didn't change anything between the load earlier this afternoon and the load that I'm attempting with the new files.

**Comment by dicksonlaw583** [comment]
Try dividing your CSV into smaller chunks and processing them one by one. There might have been an entry that isn't processing correctly, or the upload might be too big.

Also, the warning message should go away if you change that `protected function _redirectAfterEdit()` line to `protected function _redirectAfterEdit($record)`.
